version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tapo-backend
    ports:
      - "8000:8000"
    env_file:
    - ./backend/.env
    
  frontend:
    build: ./frontend
    container_name: tapo-frontend
    ports:
      - "8501:8501"
    env_file:
    - ./frontend/.env
